library(shinydashboard)
library(shinyjs)
library(shinyWidgets)
library(ggplot2)
library(ggthemes)
library(plotly)
library(reactR)
library(reactable)
library(waiter)
library(tidyr)
library(dplyr)
library(furrr)
library(future)



source("gerar_pop_inicial.R")
source("func_sobrevivencia.R")
source("modelo.R")
source("num_summary.R")
source("df_summary.R")
source("cv.R")
source("num_mode.R")
source("num_format.R")

